### ISSUE TITLE
Increase hitSlop of back button on Android

### ISSUE THREAD

**Issue by ferrannp** [react-navigation/stack#125]
### Current Behavior

- If you click the back button in the toolbar, it is really easy to miss. I saw several people missing (because they usually click on the left corner).

### Expected Behavior

- Open any native app like GMail, the icon is much more easy to click (all is clickable, like much more padding). I never missed in a native app.

### How to reproduce

Just create a stack navigator with two screens and navigate to a screen (so it has a back button).

My own button for `HeaderRight`:
![screenshot 2019-01-24 at 15 55 50](https://user-images.githubusercontent.com/774577/51686942-afe34f80-1ff1-11e9-9de5-e849a6a720c8.png)

Default back button from `react-navigation` that is hard to click:
![screenshot 2019-01-24 at 15 56 20](https://user-images.githubusercontent.com/774577/51686945-b2de4000-1ff1-11e9-9c8d-9fb94a5a11ab.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.8
| react-native     | 0.57.8
| node             | 10.11.0
| npm or yarn      | 6.5.0

**Comment by satya164** [comment]
The hitSlop should be okay in the latest alpha. Please let me know if you're still having issues.

**Comment by ravirajn22** [comment]
The issue is not fixed, back button does not have any hitSlop, moreover the Android back button in react-navigation-stack still uses react-native TouchableNativeFeedback but not from react-native-gesture-handler. I have verified in a latest sample project with following config.

```
"react-native-gesture-handler": "^1.4.1",
"react-native-reanimated": "^1.2.0",
"react-native-screens": "^2.0.0-alpha.3",
"react-navigation": "^4.0.5",
"react-navigation-stack": "^1.8.0"
```
### **React-navigation back button area**
![react-navigation-back-button](https://user-images.githubusercontent.com/10977864/65152640-f89abd80-da45-11e9-9ffe-6b8e1eea87e9.png)


### **Native back button area**
![native-back-button](https://user-images.githubusercontent.com/10977864/65152663-051f1600-da46-11e9-8fab-64944bb66369.png)

The above image shows the difference in touchable area between the react-navigation and native back buttons. In native back button the whole square surrounding the back icon is touchable whereas in react-navigation-stack only the smaller square surrounding the back icon is touchable. Please fix this, thanks.

@brentvatne @osdnk @satya164
