### ISSUE TITLE
`react-native-screens` should be an optional dependency instead of peer

### ISSUE THREAD

**Issue by apexskier** [react-navigation/stack#142]
As I understand it from [`react-native-screens` documentation](https://www.npmjs.com/package/react-native-screens#usage-with-react-navigation-without-expo) and my own experience, it's not actually required for react navigation to work. This means it should be in the [`optionalDependencies`](https://docs.npmjs.com/files/package.json#optionaldependencies) section of the package.json instead of `peerDependencies`. This'll avoid the following warnings when installing:

```
warning "react-navigation > react-navigation-drawer@1.2.1" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-stack@1.4.0" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-tabs@1.1.4" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
```

Related to https://github.com/react-navigation/drawer/issues/80, https://github.com/react-navigation/tabs/issues/141

**Comment by satya164** [comment]
You don't need to enable it, but it still needs to be installed for React Navigation to work. This is because we import the module in the code and metro doesn't support optionally importing a module.

So even if it's optional in the sense that you don't need to use it, that's not true in the sense of the package manager and bundler (which `optionalDependencies` and `peerDependencies` are intended for). Not installing or failing to install it is going to fail the build.

I'm closing the issue since it's not possible to make it an optional dependency. It needs to be a peer dependency.

**Comment by apexskier** [comment]
Okay, thanks for the additional context. I still think the warning indicates an issue and this should be moved to `optionalDependencies` or just removed from peer dependencies completely.

Since [`@react-navigation/native` is a peer dependency](https://github.com/react-navigation/stack/blob/c141c24/package.json#L75) and has an [explicit dependency on `react-native-screens`](https://github.com/react-navigation/native/blob/d54c359/package.json#L95), it's not necessary to also include `react-native-screens` as a peer dependency here, since you're guaranteed for it to be installed if you satisfy the `@react-navigation/native` peer dependency. (to your "it still needs to be installed for React Navigation to work" point).

If it's removed or moved, the warning won't show up for people who don't directly use `react-native-screens`.

**Comment by sospedra** [comment]
Why not a normal dependency?
