### ISSUE TITLE
Full web support on v2+

### ISSUE THREAD

**Issue by brunolemos** [react-navigation/stack#148]
I'd love to use this new version by @satya164 on my projects but they are mostly universal projects that use react-native-web. Is that planned?

I see v2 is using `react-native-gesture-handler` and `react-native-reanimated`, they don't have web support yet (https://github.com/kmagiera/react-native-gesture-handler/issues/581, https://github.com/kmagiera/react-native-reanimated/issues/169).

@EvanBacon [made gesture handler work in the web](https://twitter.com/Baconbrix/status/1141240199407517696?s=20), so maybe we could use that? (pinged him [here](https://github.com/kmagiera/react-native-gesture-handler/issues/581#issuecomment-504773788)).

**Comment by tehOPEologist** [comment]
getting web support for this package has such a need from applications that want to use react-navigation across multiple platforms.  i know that expo has experimental support for react-navigation on the web, but a lot of react-native applications don't leverage expo at all, because of custom stuff expo apps can't support (easily).  is there any progress on web support?  please let us know, thanks!

**Comment by brunolemos** [comment]
.
