### ISSUE TITLE
headerTitle type is incorrect

### ISSUE THREAD

**Issue by jpaas** [react-navigation/stack#225]
Currently the type for headerTitle is:
`headerTitle?: string;`

But it also should accept a React element or component.

**Comment by peterkuiper** [comment]
Also, `headerLeft` only allows `React.FunctionComponent<HeaderBackbuttonProps>`, thus this isn't allowed:

```
headerLeft: (
  <RNView>
    <RNText>headerLeft</RNText>
  </RNView>
),
```

We are also using the following styling on `headerLeftContainerStyle`:

```
leftButton: {
  marginLeft: 5,
  flexDirection: 'row',
  alignItems: 'center',
},
```

This isn't allowed due to `headerLeftContainerStyle?: StyleProp<ViewStyle>;`. Can the `NavigationStackOptions` types be relaxed a bit more or is there some specific reason this isn't allowed?

**Comment by satya164** [comment]
Fixed in 3702f17

**Comment by SimenB** [comment]
Using this I get `Invariant Violation: Invariant Violation: Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)`. Using 1.8.1 it works fine.

This is passing a `React.FC` as `headerTitle`

**Comment by satya164** [comment]
Please change it to a function. It was a mistake which allowed you to use function components (the component will re-mount each render this way). You can extract the component out and then do:

```js
headerTitle: () => <YourComponent />
```

**Comment by SimenB** [comment]
Yup, that's what I ended up doing 👍
