### ISSUE TITLE
Performance issues with new implemention of Stack

### ISSUE THREAD

**Issue by osdnk** [react-navigation/stack#252]
Arter reimplementing stack with React Native Reanimated, we face some performance issues. It's mostly visible on low-level device and it's very easy to observe. We see that click and invoking `push` or `navigate` does not always have immediate effect. It takes some short delay however it leads to not a smooth experience. 
So what to do? We're not sure!

We're tried many optimizations for Reanimated. We added support for batching, memoization, procedural nodes, but still, we see that it could at least a bit better. We still see that while pushing a new screen bridge is intensively used wondering how we can get rid of these problems.

**Comment by slorber** [comment]
Hi,

I've also noticed this kind of behavior when using reanimated, when rendering a lot of nodes. Probably not totally related to navigation, because I can see this also on a good android device by adding a few reanimated components to my screen: mounting/updating is expensive. I've been able to overcome update issues by memoizing more aggressively the reanimated nodes but the mounting is still slow.

Not sure how this can be fixed in this lib, isn't it related to too much reanimated nodes having to cross the bridge?

Maybe this will be solved by Fabric if serialization cost is gone?

**Comment by sebinq** [comment]
What about declaring most frequently used screen transitions/animations directly in native?

**Comment by Daavidaviid** [comment]
We also noticed this on Android mostly. When we click on a button to trigger a `navigation.navigate()` to a new screen using the iOS 13 modal mode, there is a delay before the new screen appears on screen.

With the react native performance tool we can notice a drop rate:

Before opening a modal:
![before_modal](https://user-images.githubusercontent.com/32457364/70312142-4936e100-1813-11ea-985a-8abfd4f84c1e.png)

After: 
![after_modal](https://user-images.githubusercontent.com/32457364/70312167-5653d000-1813-11ea-983e-8b225b7330c7.png)

And we can definitely feel it when using the app.

**Comment by satya164** [comment]
Closing since we have migrated to Animated.
