### ISSUE TITLE
Unable to resolve module 'react-native-safe-area-context'

### ISSUE THREAD

**Issue by eae-christian** [react-navigation/stack#323]
Hi, I did the upgrade of react-navigation-tabs from 1.10.3 to 2.0.1 and immediately after restarting the application I found that the following error (attached photo)

![Screenshot 2020-01-02 at 09 22 37](https://user-images.githubusercontent.com/49148186/71660063-c6d20c00-2d41-11ea-89e9-c38a36d0156d.png)

Description of my environment

"react": "16.11.0",
"react-native": "0.61.5",
"react-native-gesture-handler": "^1.5.3",
"react-native-screens": "^2.0.0-alpha.22",
"react-navigation": "^4.0.10",
"react-navigation-drawer": "^2.3.3",
"react-navigation-stack": "^2.0.1",
"react-navigation-tabs": "^2.6.2",

I'm just developing for iOS

Do you have any solution?
Thank you

**Comment by mcruz19** [comment]
I'm having the same issue, but i'm having two issues. This one and **"bundling failed: Error: Unable to resolve module `@react-native-community/masked-view` from `node_modules/react-navigation-stack/lib/module/vendor/views/MaskedView.js`: @react-native-community/masked-view could not be found within the project."**

Any ideas?

**Comment by satya164** [comment]
Install those dependencies in your project.

**Comment by eae-christian** [comment]
to make it clearer, install
 - "@react-native-community/masked-view"
 - "react-native-safe-area-context"

**Comment by tobias-zucali** [comment]
Why don't you want to put those in the dependencies list? Was this change on purpose?

**Comment by mansdahlstrom1** [comment]
Having the same issue, does the error originate from missing dependencies? or am i missing something here?

**Comment by satya164** [comment]
@tobias-zucali because these dependencies contain native code that needs to be linked, and they need to be your project's dependency to be linked correctly. making them a regular dependency will mean there will be other issues such as conflicting versions, unable to link etc.

@mansdahlstrom1 you need to follow the instructions in our [getting started guide](https://reactnavigation.org/docs/en/getting-started.html#install-into-an-existing-project) to setup React Navigation and [installation instructions for stack](https://reactnavigation.org/docs/en/stack-navigator.html) to use the stack navigator.

we're not trying to make your life difficult. react native doesn't include many features and it's necessary to use third party native modules to achieve the behavior we want. the setup is the way it is because it's not possible to make it easier.

we've tried to document all of the steps, please follow the documentation before opening issues. it'll save both of us time.

**Comment by tobias-zucali** [comment]
@satya164 thanks for the explanation!

**Comment by uladzislau-stuk** [comment]
@satya164 thanks you!

**Comment by bekagaw653** [comment]
Already Solved [Here](https://icetutor.com/question/getting-this-error-error-bundling-failed-error-unable-to-resolve-module-react-native-safe-area-context/)

**Comment by ASD-Black** [comment]
npm install --save @react-native-community/masked-view

install this
worked foe me

**Comment by ketanambekar1** [comment]
> to make it clearer, install
> 
> * "@react-native-community/masked-view"
> * "react-native-safe-area-context"

Yes it worked: :)
npm install --save @react-native-community/masked-view
npm install react-native-safe-area-context

**Comment by joel2035** [comment]
this wocked for me

**Comment by SupriyaGo** [comment]
> 
> 
> to make it clearer, install
> 
>     * "@react-native-community/masked-view"
> 
>     * "react-native-safe-area-context"

after installing these, app is getting crashed, how to solve this issue?

**Comment by eae-christian** [comment]
> > to make it clearer, install
> > ```
> > * "@react-native-community/masked-view"
> > 
> > * "react-native-safe-area-context"
> > ```
> 
> after installing these, app is getting crashed, how to solve this issue?

try
remove app (simulator or device)
clean/clear build (xcode or android studio)
then run "npm run start -- --reset-cache"

maybe, this can help you

**Comment by SupriyaGo** [comment]
solved- https://github.com/react-navigation/react-navigation/issues/6892#issuecomment-588113613
