### ISSUE TITLE
2.0.x Not responding to touching right after close animation

### ISSUE THREAD

**Issue by frankyjuang** [react-navigation/stack#330]
After close animation (removing a screen) finish, the screen freeze for about half second, not responding to touching. Only happens when `animationEnabled` is true, and open animation (adding a screen) is not affected. Not sure if it's related to `TransitionSpec` because I feel like using `TransitionIOSSpec` is a lot worse (freeze longer) than `FadeOutToBottomAndroidSpec`.

**Comment by Jekiwijaya** [comment]
I think this commit fixed this issue
https://github.com/react-navigation/navigation-ex/commit/15fe3ebb51266fcd4b9a4c0baf59424bd92ff054

but I tried to quickly navigate after back using gesture in IOS, it feels jagged because gesture trigger StackAction.pop() and called a bit latter after the animation being done, I tried fix in this commit: 
https://github.com/react-navigation/navigation-ex/pull/244

cc: @satya164

**Comment by frankyjuang** [comment]
Thanks! Haven't tested yet. @Jekiwijaya could you elaborate a bit more why removing `PointerEventsView` helps?

**Comment by Jekiwijaya** [comment]
It's because previously every screen on the stack the pointerEvent are disabled except the topmost screen. And now the commit only disabled while the screen is closing

**Comment by appdrop** [comment]
Same for me. Works in `1.10.2`, doesn't work in 2.0.15

#353 related

**Comment by satya164** [comment]
I believe this shouldn't be an issue anymore. Please try the latest version and let me know.
