### ISSUE TITLE
Unclear about roadmap and versioning stack v2, stack v1, parent project v5

### ISSUE THREAD

**Issue by shamilovtim** [react-navigation/stack#332]
I'm unclear about the versioning of the overall project and how it pertains to it packages.

Is it intended for users of stack v1 to migrate to stack v2? Toward that end, I did not see a migration guide in the patch notes. Is stack v2 intended for users of navigation v4 or v5? I know there's a v5 that's coming out that's supposed to be a complete overhaul and it was my understanding that work on v4 would be completely stopped a month or two ago. However I see there's still active work on these dependent packages and I'm not understanding whether that means this is work for v5?

Which versions of react-navigation and its dependencies should we be starting with today for a long term application?

**Comment by satya164** [comment]
> Is it intended for users of stack v1 to migrate to stack v2
Yes

> Is stack v2 intended for users of navigation v4 or v5
v5 is still under development in a separate repo https://github.com/react-navigation/navigation-ex

>  I did not see a migration guide in the patch notes
The changelog lists all of the breaking changes, in addition upgrading gives you warnings with instructions on what to change.

> my understanding that work on v4 would be completely stopped a month or two ago
A lot of people are still using v4 in production. It'll be supported for a while because it'll be difficult to upgrade to v5 without a lot of work and it'll suck for people to suddenly not have bug fixes. v4 is going to be still supported with bug fixes even after v5 is released.

Stack v2 is a backport of the stack in v5. If you upgrade to this version of Stack, it'll be easier to upgrade to v5 in future because the options are the same.

Anyway, until v5 is officially released as stable, any other release doesn't have anything to do with it. We'll do a blog post when v5 is stable.

> Which versions of react-navigation and its dependencies should we be starting with today for a long term application?

That's upto you if you want to choose stable version and migrate later or want to use prerelease version. If you don't mind breaking changes before final release, you can go with v5. If you can't afford breaking changes, stay with stable version.

**Comment by shamilovtim** [comment]
Thank you @satya164

**Comment by makarkotlov** [comment]
> > Is it intended for users of stack v1 to migrate to stack v2
> 
> Yes
> 
> > Is stack v2 intended for users of navigation v4 or v5
> 
> v5 is still under development in a separate repo https://github.com/react-navigation/navigation-ex
> 
> > I did not see a migration guide in the patch notes
> 
> The changelog lists all of the breaking changes, in addition upgrading gives you warnings with instructions on what to change.
> 
> > my understanding that work on v4 would be completely stopped a month or two ago
> 
> A lot of people are still using v4 in production. It'll be supported for a while because it'll be difficult to upgrade to v5 without a lot of work and it'll suck for people to suddenly not have bug fixes. v4 is going to be still supported with bug fixes even after v5 is released.
> 
> Stack v2 is a backport of the stack in v5. If you upgrade to this version of Stack, it'll be easier to upgrade to v5 in future because the options are the same.
> 
> Anyway, until v5 is officially released as stable, any other release doesn't have anything to do with it. We'll do a blog post when v5 is stable.
> 
> > Which versions of react-navigation and its dependencies should we be starting with today for a long term application?
> 
> That's upto you if you want to choose stable version and migrate later or want to use prerelease version. If you don't mind breaking changes before final release, you can go with v5. If you can't afford breaking changes, stay with stable version.

Where can I find that changelog?
