### ISSUE TITLE
[v2] didFocus event is very slow

### ISSUE THREAD

**Issue by lorenc-tomasz** [react-navigation/stack#386]
On v1 `didFocus` occured after +- 1 second. On v2 didFocus happens after +- 10 seconds. 

```
...
// also tried in `constructor`
componentDidMount() {
  this.props.navigation.addListener('willFocus', () => alert('will focus'))
  this.props.navigation.addListener('didFocus', () => alert('did focus'))
}
```

`willFocus` works as expected.

**Comment by lorenc-tomasz** [comment]
`willFocus`, `didFocus`, `willBlur` , `didBlur`  not fire in some cases. I cannot find any pattern for that :(

v2 is awesome but has to many regresions comparing to v1. I wll return to v1.

**Comment by satya164** [comment]
Can you describe more what are the many regressions?

**Comment by lorenc-tomasz** [comment]
Maybe 'many' was to big word. But navigation events fires or not, and if they fire they have delay, especially `didFocus`. Cannot find any pattern for that and the reason of this issue. Also hiding keyboard is duplicating header size when `android:windowSoftInputMode` is `adjustPan` (https://github.com/react-navigation/stack/issues/326). All this works OK on v1.

**Comment by satya164** [comment]
> But navigation events fires or not

Can you provide repros when they don't fire? Navigation events have been buggy in v4 for quite a while.

**Comment by lorenc-tomasz** [comment]
Will try to prepare the example repo on weekend.

**Comment by Evan-Younan** [comment]
+1 Also running into this issue.

**Comment by Evan-Younan** [comment]
After looking into this a little more, it looks like limiting the transition duration between screens makes this process harder to reproduce. 
I was using:

`TransitionPresets.SlideFromRightIOS` 

before when transitioning between screens. I tried 

`TransitionPresets.FadeFromBottomAndroid`

since its duration is 150ms and it seems like the events are firing quicker.

**Comment by satya164** [comment]
Shouldn't be an issue in latest version (2.1.0). Please try and lemme know.

**Comment by Evan-Younan** [comment]
I just upgraded to 2.1.0 and the issue still persists.

**Comment by satya164** [comment]
@Evan-Younan I'm not following what the issue is. `willFocus` and `willBlur` usually fire at the beginning of animation, `didFocus` and `didBlur` fire at the end of animation which will take a while. I don't believe the mentioned number of 10 seconds, but in case of spring animation it can indeed take a while to fire those events.

If you want them to fire sooner, you need to tweak your animations to finish sooner by tweaking `transitionSpec`: https://reactnavigation.org/docs/en/stack-navigator.html#animation-related-options

Here's the config to get what v1 used to use:

```js
const IOSTransitionSpec = {
  duration: 500,
  easing: Easing.bezier(0.2833, 0.99, 0.31833, 0.99),
  timing: Animated.timing,
};

// ...

defaultNavigationOptions: {
  transitionSpec: { open: IOSTransitionSpec, close: IOSTransitionSpec },
};
```

**Comment by Evan-Younan** [comment]
I'll open a new issue.
