### ISSUE TITLE
Remove requestAnimationFrame from header

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/stack#41]
Ensure that the ripple works as expected. https://github.com/react-navigation/react-navigation/issues/3509#issuecomment-431793863

**Comment by satya164** [comment]
I think it's there because the `onPress` doesn't block the touch. So ripple will feel more responsive when doing this. Without it, the ripple won't show until `onPress` has returned, so it won't show if the navigation event takes a little longer to complete for some reason.

IMO there are many issues and glitches in debugger regarding animations. We can't really fix them, and removing it might have a worse UX in normal apps.

**Comment by jigarmistry** [comment]
I agree with @satya164 but in android debug build header button's click not working( it is good in release build & iOS) not only the back button. I can not share my project but it is the case. Can we get temporary solution if any?

**Comment by satya164** [comment]
We can't really fix the issues with the debugger.

**Comment by brentvatne** [comment]
maybe you could work around like this if you want? `window.requestAnimationFrame = (cb) => window.setTimeout(cb, 0);`

**Comment by satya164** [comment]
Closing coz it's not actionable
