### ISSUE TITLE
Possibly change the unmount sequence when using popToTop or otherwise unmounting multiple screens

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/stack#42]
Moved from https://github.com/react-navigation/react-navigation/issues/4837

**Comment by satya164** [comment]
Closing this since the way `popToTop`, `reset` etc. work is now changed in the latest alpha. Instead of unmounting one by one, the latest alpha unmounts all screens keeping the last screen until the animation finishes.

I think this is also an implementation detail as mentioned in the issue and something the user shouldn't rely on.
