### ISSUE TITLE
Test and fix layout issues in the header when using increased text size for accessibility

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/stack#45]
![bug](https://user-images.githubusercontent.com/90494/47608829-e5739f00-d9e8-11e8-821c-dc086ad9fe30.jpg)

**Comment by pzatorski** [comment]
Hey @brentvatne I have reproduced bad behaviour of header. The question is if we want to resize text in the header when the accessibility for Text Size change? If yes I assume that the ``` `< ${title}` ``` should change to  ``` `< Back` ``` .  iOS itself doesn't resize header text when increased text size for accessibility.
Thanks and please let me know what we do with it. I'm keen to help.

**Comment by brentvatne** [comment]
@pzatorski - I think we want to change it to `< Back` in this situation! :) your help would be much appreciated!

**Comment by pzatorski** [comment]
Hey @brentvatne, I look at this problem over the weekend and I couldn't find solution for it..
We update the state in render of Component `HeaderBackButton` calling this function `_onTextLayout`

```
  _onTextLayout = e => {
    if (this.state.initialTextWidth) {
      return;
    }
    this.setState({
      initialTextWidth: e.nativeEvent.layout.x + e.nativeEvent.layout.width
    });
  };
```
If user enters the screen we check the layout and we display render correct "titleText"
("< Back" or "< Title") and we save it to the state. But when we update the `Text Size` from Settings
in iOS, it still has the same value - understandable because we do not return anything when we have `initialTextWidth` from state.

When I remove:
```
    if (this.state.initialTextWidth) {
      return;
    }
```
And now when we update the `Text Size` from settings it listen `nativeEvent.layout` all the time - Great!
The problem occurs when `titleText` is updated let's say from "< Title"title` to "< Back".. - it goes inside the loop..

We change the text in render of the component so the function "doesn't know" on which text it should listen for "Title" or "Back"

Any ideas, how to solve it?
