### ISSUE TITLE
StackViewStyleInterpolator forHorizontal has invalid style

### ISSUE THREAD

**Issue by lhanwool** [react-navigation/stack#54]
The return value for "forHorizontal" has overlayOpacity which is an invalid style.  I believe it should be opacity.

**Comment by luck2011** [comment]
Same here

**Comment by fxdemolisher** [comment]
overlayOpacity and shadowOpacity are actually in use: https://github.com/react-navigation/react-navigation-stack/blob/master/src/views/StackView/StackViewCard.js#L80

They are undocumented but are in use for some modal transitions.

**Comment by lhanwool** [comment]
@fxdemolisher Are you sure?  I get a yellow box warning with overlayOpacity and I can see it's not performing the opacity change during the transition.

**Comment by fxdemolisher** [comment]
@lhanwool my project is on `^3.0.9` version at the moment an we do not get any warnings with our custom interpolator. Do you have an example of what your usage looks like?

**Comment by lhanwool** [comment]
@fxdemolisher Ummm, I'm not sure why you don't see the issue.  Looking at the code you referred to in your prior comment: https://github.com/react-navigation/react-navigation-stack/blob/master/src/views/StackView/StackViewCard.js#L80
```        {overlayOpacity ? (
          <Animated.View
            pointerEvents="none"
            style={[styles.overlay, { opacity: overlayOpacity }]}
          />
        ) : null}```

overlayOpacity is renamed as overlay.  We've had to do the same in our code since overlayOpacity isn't a real style.

**Comment by fxdemolisher** [comment]
My project is on typescript vs flowtype so that may be why we are not seeing the same warnings as you. 

Just to make sure I'm on the same page though. From what I understand, screen interpolators are allowed to return two extra keys in their return type that are not part of React's ViewStyle type. These are `overlayOpacity` and `shadowOpacity`. What StackViewCard does is read those keys from the style object provided by the interpolator. If `overlayOpacity` is defined an extra view is rendered in the card with `opacity` set to `overlayOpacity` as you see in the piece of code referenced above. `shadowOpacity` operates on the same principle.

Unless you are using your own implementation of StackView or some middleman view that utilizes the styles coming from the interpolators as-is (e.g. unfiltered for overlayOpacity, etc) you should not be seeing any warnings. I believe this is due to a style object containing `overlayOpacity` never making it to the style prop of any of React's view classes.

What am I missing?

**Comment by lhanwool** [comment]
That's basically it, we're utilizing the styles as-is in our transitionConfig.  It seems like it's an oversight when you look at the other methods (i.e. forFadeFromBottomAndroid, forFadeToBottomAndroid, and forFade) all return opacity instead of overlayOpacity.

Not a big deal since it takes 2 lines of code to reassign overlayOpacity to opacity.  But if I'm having to do it in my code and if the implementation of StackViewCard is also doing it, then maybe it should be fixed in StackViewStyleInterpolator and also be made consistent with the other methods mentioned.

**Comment by fxdemolisher** [comment]
I think the main difference between your usage and StackViewCard's is that the later uses opacity for the screen's style and overlayOpacity as the opacity style for an additional view that represents the dimmed overlay. I don't know if assigning overlayOpacity to opacity in your own StackView will do what you expect it to do.

Am I right to assume you are using a custom StackView in your navigator?

**Comment by lhanwool** [comment]
Actually, StackViewCard uses shadowOpacity and opacity.  It reassigns overlayOpacity to opacity.  There is no overlayOpacity style.

We're using a custom transitionConfig.

**Comment by fxdemolisher** [comment]
@lhanwool we may need to take this conversation offline. What I think I am missing is how you are using the style being returned by the styleInterpolator. Unless you feed it into a RN view (e.g. `<View style={...interpolatedStyle} />`) directly I don't see where the yellow box would happen. The standard StackView knows how to deal with overlayOpacity. As I mentioned above, it doesn't actually alias it to opacity, instead it adds an extra View into the hierarchy that acts as the overlay.

**Comment by satya164** [comment]
Closing since this is not relevant in the latest alpha anymore.
