### ISSUE TITLE
how to config waitFor for PanGestureHandler of StackViewLayout

### ISSUE THREAD

**Issue by gaodeng** [react-navigation/stack#56]

**Comment by satya164** [comment]
Can you describe your use case?

**Comment by gaodeng** [comment]
@satya164  RNGH inside stackviewlayout

**Comment by Taylor123** [comment]
Is there any example of this?

My use case is having a `react-native-tab-view` within a `StackNavigator`. I have configured the `StackNavigator` to allow a swipe back gesture from anywhere on the screen using `gestureResponseDistance.horizontal`. This swipe back gesture should only be allowed to happen when the `react-native-tab-view` is on index 0.

I've tried setting navigation params `onIndexChange`, but this results in a bad UX since it takes a long time from the gesture start to the navigation params being updated. Would love a way to have the `StackGestureHandler` to only be enabled when the `react-native-tab-view` is on index 0
